/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Widyatama
 */
public class GuiClient extends javax.swing.JFrame {

    /**
     * Creates new form GuiClient
     */
    public GuiClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaLabel = new javax.swing.JLabel();
        jenisLabel = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboCPU = new javax.swing.JComboBox<>();
        motherBoardLabel = new javax.swing.JLabel();
        comboMotherBoard = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ramComboBox = new javax.swing.JComboBox<>();
        storageLabel = new javax.swing.JLabel();
        storageCombo = new javax.swing.JComboBox<>();
        vgaLabel = new javax.swing.JLabel();
        vgaCombo = new javax.swing.JComboBox<>();
        psuLabel = new javax.swing.JLabel();
        psuCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        caseCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        namaLabel.setText("Nama");

        jenisLabel.setText("Pilih Jenis");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        comboBox.setEditable(true);
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah satu", "Dikirim Kerumah (Ongkir 20000)", "Ambil ditoko" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        jButton2.setText("Tampilkan Checkout");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        alamatLabel.setText("Alamat");
        alamatLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                alamatLabelComponentHidden(evt);
            }
        });

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });

        jLabel1.setText("Processor");

        comboCPU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah satu", "Intel Core i3-8100  - Rp 2.100.000", "Intel Core i5-7400  - Rp 2.800.000", "Intel Core i5-9400F - Rp 2.470.000", "Intel Core i5-9600K - Rp 3.980.000", "Intel Core i7-9700K - Rp 6.630.000" }));
        comboCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCPUActionPerformed(evt);
            }
        });

        motherBoardLabel.setText("MotherBoard");

        comboMotherBoard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah satu", "Asrock B360M Pro4 - Rp 1.320.000", "ASUS ROG STRIX H370-F Gaming - Rp 2.680.000", "ASUS TUF B360 PRO Gaming - Rp 2.099.000", "Gigabyte B360 AORUS Gaming 3 - Rp 1.999.000", "MSI B360 GAMING PRO CARBON - Rp 1.950.000" }));

        jLabel5.setText("RAM");

        ramComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah satu", "Apacer Panther Golden 8GB DDR4 PC19200 2400MHz - Rp 680.000", "Corsair Vengeance LPX (2x4) 8GB 2666MHz - Rp 885.000", "Corsair Vengeance RGB 16GB (2x8GB) DDR4 2666MHz - Rp 1.810.000", "TEAM T-Force Delta RGB (2x8) 16GB DDR4 kit 3000MHz - Rp 1.740.000", "Corsair Vengeance RGB 32GB (2x16GB) DDR4 3200MHz   - Rp 3.775.000" }));

        storageLabel.setText("Storage");

        storageCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah satu", "Seagate BarraCuda 1TB HDD - Rp 640.000", "Seagate BarraCuda 2TB HDD - Rp 890.000", "WD Caviar Blue 1 TB HDD   - Rp 635.000", "WD Caviar Blue 2 TB HDD   - Rp 895.000" }));

        vgaLabel.setText("Graphic Card");

        vgaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah satu", "Asrock Radeon RX 570 PHANTOM GAMING D 4GB GDDR5 - Rp 1.950.000", "SAPPHIRE NITRO+ Radeon RX 580 8GD5 OC - Rp 3.650.000", "ASUS Dual GeForce GTX 1660 Ti OC edition 6GB GDDR6 - Rp 4.750.000", "ASUS DUAL GeForce RTX 2060 OC edition 6GB GDDR6 - Rp 6.400.000", "ASUS ROG Strix GeForce RTX 2080 Ti OC edition 11GB GDDR6 - Rp 24.990.000", "Tidak Memilih" }));

        psuLabel.setText("Power Supply");

        psuCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah satu", "Corsair CX550M Modular 80+ Bronze Certified - Rp 1.130.000", "Corsair CX650M - 650 Watt 80+ Bronze Certified - Rp 1.230.000", "Corsair VS450 - 450W - Rp 545.000", "Corsair VS550 - 550W - Rp 750.000", "COUGAR VTE500 500W 80+ Bronze Certification - Rp 680.000" }));

        jLabel3.setText("CPU Case");

        caseCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah satu", "Cooler Master MasterBox MB510L Tempered Glass Gaming Case - Rp 820.000", "Cooler Master MasterBox TD500 Diamond Cut Gaming Case - Rp 1.070.000", "COUGAR MX340 Tempered Glass Mid Tower Gaming Case - Rp 590.000", "COUGAR Panzer G - Rp 1.425.000", "Cube Gaming Camarillo Tempered Glass Clean Design Case - Rp 490.000" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Toko Komputer KlikMeteor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jenisLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(namaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(alamatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(12, 12, 12)))
                                                        .addGap(95, 95, 95))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addGap(93, 93, 93)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(motherBoardLabel)
                                                    .addGap(78, 78, 78)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(118, 118, 118)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(storageLabel)
                                            .addGap(186, 186, 186)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vgaLabel)
                                        .addGap(162, 162, 162)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(psuLabel)
                                    .addGap(159, 159, 159)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(177, 177, 177)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(alamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vgaCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caseCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(psuCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(storageCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ramComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboMotherBoard, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboCPU, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nama)))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {alamat, caseCombo, comboBox, comboCPU, comboMotherBoard, nama, psuCombo, ramComboBox, storageCombo, vgaCombo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nama))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBox))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(alamatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(comboCPU))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(motherBoardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(comboMotherBoard))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(ramComboBox))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(storageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(storageCombo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(vgaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(vgaCombo)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(psuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(psuCombo))
                        .addGap(18, 18, 18)
                        .addComponent(caseCombo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        
    }//GEN-LAST:event_namaActionPerformed

    private void alamatLabelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_alamatLabelComponentHidden
        
    }//GEN-LAST:event_alamatLabelComponentHidden

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void comboCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCPUActionPerformed
        
    }//GEN-LAST:event_comboCPUActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
    }//GEN-LAST:event_formMouseClicked

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        Proses proses = new Proses();
        Karyawan karyawan = new Karyawan();
        String itemText = (String) comboBox.getSelectedItem();
        String metodeAmbil=null;
        String alamatRumah=null;
         if(itemText.equalsIgnoreCase("Ambil ditoko")){
            alamatLabel.setVisible(false);
            alamat.setVisible(false);
            alamatRumah="Jln. Gajayana IV No.15, Dinoyo, Malang";
            metodeAmbil="ambil";
        }
        else{
            alamatRumah = alamat.getText();
            alamatLabel.setVisible(true);
            alamat.setVisible(true);
            metodeAmbil="kirim";
        }    
        String cpu = null;
        String comboBoxCPU = (String) comboCPU.getSelectedItem();
        if(comboBoxCPU.equalsIgnoreCase("Intel Core i3-8100  - Rp 2.100.000")){
            cpu="i38100";
        }
        else if(comboBoxCPU.equalsIgnoreCase("Intel Core i5-7400  - Rp 2.800.000")){
            cpu="i57400";
        }
        else if(comboBoxCPU.equalsIgnoreCase("Intel Core i5-9400F - Rp 2.470.000")){
            cpu="i59400";
        }
        else if(comboBoxCPU.equalsIgnoreCase("Intel Core i5-9600K - Rp 3.980.000")){
            cpu="i59600";
        }
        else if(comboBoxCPU.equalsIgnoreCase("Intel Core i7-9700K - Rp 6.630.000")){
            cpu="i79700";
        }
        else{
            cpu="0";
        }
        String alamatText = alamat.getText();

        String namePembeli = nama.getText();

        String motherboard = null;
        String comboBoxmobo = (String) comboMotherBoard.getSelectedItem();
        if(comboBoxCPU.equalsIgnoreCase("Asrock B360M Pro4 - Rp 1.320.000")){
            motherboard="asrockb360m";
        }
        else if(comboBoxmobo.equalsIgnoreCase("ASUS ROG STRIX H370-F Gaming - Rp 2.680.000")){
            motherboard="asusrogh370";
        }
        else if(comboBoxmobo.equalsIgnoreCase("ASUS TUF B360 PRO Gaming - Rp 2.099.000")){
            motherboard="asustufb360";
        }
        else if(comboBoxmobo.equalsIgnoreCase("Gigabyte B360 AORUS Gaming 3 - Rp 1.999.000")){
            motherboard="gigabyteb360";
        }
        else if(comboBoxmobo.equalsIgnoreCase("MSI B360 GAMING PRO CARBON - Rp 1.950.000")){
            motherboard="msib360";
        }
        else{
            motherboard="0";
        }

        String ram = null;
        String comboBoxRam = (String) ramComboBox.getSelectedItem();
        if(comboBoxRam.equalsIgnoreCase("Apacer Panther Golden 8GB DDR4 PC19200 2400MHz - Rp 680.000")){
            ram="apacer8gb";
        }
        else if(comboBoxRam.equalsIgnoreCase("Corsair Vengeance LPX (2x4) 8GB 2666MHz - Rp 885.000")){
            ram="corsair8gb";
        }
        else if(comboBoxRam.equalsIgnoreCase("Corsair Vengeance RGB 16GB (2x8GB) DDR4 2666MHz - Rp 1.810.000")){
            ram="corsair16gb";
        }
        else if(comboBoxRam.equalsIgnoreCase("TEAM T-Force Delta RGB (2x8) 16GB DDR4 kit 3000MHz - Rp 1.740.000")){
            ram="team16gb";
        }
        else if(comboBoxRam.equalsIgnoreCase("Corsair Vengeance RGB 32GB (2x16GB) DDR4 3200MHz   - Rp 3.775.000")){
            ram="corsair32gb";
        }
        else{
            ram="0";
        }

        String storage = null;
        String comboStorage = (String) storageCombo.getSelectedItem();
        if(comboStorage.equalsIgnoreCase("Seagate BarraCuda 1TB HDD - Rp 640.000")){
            storage="seagate1tb";
        }
        else if(comboStorage.equalsIgnoreCase("Seagate BarraCuda 2TB HDD - Rp 890.000")){
            storage="seagate2tb";
        }
        else if(comboStorage.equalsIgnoreCase("WD Caviar Blue 1 TB HDD   - Rp 635.000")){
            storage="wd1tb";
        }
        else if(comboStorage.equalsIgnoreCase("WD Caviar Blue 2 TB HDD   - Rp 895.000")){
            storage="wd2tb";
        }
        else{
            storage="0";
        }

        String videocard = null;
        String comboVga = (String) vgaCombo.getSelectedItem();
        if(comboVga.equalsIgnoreCase("Asrock Radeon RX 570 PHANTOM GAMING D 4GB GDDR5 - Rp 1.950.000")){
            videocard="rx570";
        }
        else if(comboVga.equalsIgnoreCase("SAPPHIRE NITRO+ Radeon RX 580 8GD5 OC - Rp 3.650.000")){
            videocard="rx580";
        }
        else if(comboVga.equalsIgnoreCase("ASUS Dual GeForce GTX 1660 Ti OC edition 6GB GDDR6 - Rp 4.750.000")){
            videocard="gtx1660ti";
        }
        else if(comboVga.equalsIgnoreCase("ASUS DUAL GeForce RTX 2060 OC edition 6GB GDDR6 - Rp 6.400.000")){
            videocard="rtx2060";
        }
        else if(comboVga.equalsIgnoreCase("ASUS ROG Strix GeForce RTX 2080 Ti OC edition 11GB GDDR6 - Rp 24.990.000")){
            videocard="rtx2080ti";
        }
        else{
            videocard="0";
        }
        String psu = null;
        String comboPsu = (String) psuCombo.getSelectedItem();
        if(comboPsu.equalsIgnoreCase("Corsair CX550M Modular 80+ Bronze Certified - Rp 1.130.000")){
            psu="corsaircx550m";
        }
        else if(comboPsu.equalsIgnoreCase("Corsair CX650M - 650 Watt 80+ Bronze Certified - Rp 1.230.000")){
            psu="corsaircx650m";
        }
        else if(comboPsu.equalsIgnoreCase("Corsair VS450 - 450W - Rp 545.000")){
            psu="corsairvs450";
        }
        else if(comboPsu.equalsIgnoreCase("Corsair VS550 - 550W - Rp 750.000")){
            psu="corsairvs550";
        }
        else if(comboPsu.equalsIgnoreCase("COUGAR VTE500 500W 80+ Bronze Certification - Rp 680.000")){
            psu="cougarvte500";
        }
        else{
            psu="0";
        }

        String pccase = null;
        String comboCase = (String) caseCombo.getSelectedItem();
        if(comboCase.equalsIgnoreCase("Cooler Master MasterBox MB510L Tempered Glass Gaming Case - Rp 820.000")){
            pccase="coolermb510";
        }
        else if(comboCase.equalsIgnoreCase("Cooler Master MasterBox TD500 Diamond Cut Gaming Case - Rp 1.070.000")){
            pccase="coolertd500";
        }
        else if(comboCase.equalsIgnoreCase("COUGAR MX340 Tempered Glass Mid Tower Gaming Case - Rp 590.000")){
            pccase="cougarmx340";
        }
        else if(comboCase.equalsIgnoreCase("COUGAR Panzer G - Rp 1.425.000")){
            pccase="cougarpanzer";
        }
        else if(comboCase.equalsIgnoreCase("Cube Gaming Camarillo Tempered Glass Clean Design Case - Rp 490.000")){
            pccase="cubegaming";
        }
        else{
            pccase="0";
        }

        PesananOrder pesananOrder = new PesananOrder(proses, metodeAmbil, alamatRumah, namePembeli, cpu, motherboard, ram, storage, videocard, psu, pccase);
        karyawan.ambilOrder(pesananOrder);
    }//GEN-LAST:event_jButton2MousePressed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
       String itemText = (String) comboBox.getSelectedItem();
        String metodeAmbil=null;
        String alamatRumah=null;
         if(itemText.equalsIgnoreCase("Ambil ditoko")){
            alamatLabel.setVisible(false);
            alamat.setVisible(false);
            alamatRumah="Jln. Gajayana IV No.15, Dinoyo, Malang";
            metodeAmbil="ambil";
        }
        else{
            alamatRumah = alamat.getText();
            alamatLabel.setVisible(true);
            alamat.setVisible(true);
            metodeAmbil="kirim";
        }    
    }//GEN-LAST:event_comboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JComboBox<String> caseCombo;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JComboBox<String> comboCPU;
    private javax.swing.JComboBox<String> comboMotherBoard;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JLabel motherBoardLabel;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JComboBox<String> psuCombo;
    private javax.swing.JLabel psuLabel;
    private javax.swing.JComboBox<String> ramComboBox;
    private javax.swing.JComboBox<String> storageCombo;
    private javax.swing.JLabel storageLabel;
    private javax.swing.JComboBox<String> vgaCombo;
    private javax.swing.JLabel vgaLabel;
    // End of variables declaration//GEN-END:variables
}
